<?php

/**
 * BaseHelp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Category
 * @property Doctrine_Collection $HelpCategory
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getCategory()     Returns the current record's "Category" collection
 * @method Doctrine_Collection getHelpCategory() Returns the current record's "HelpCategory" collection
 * @method Help                setName()         Sets the current record's "name" value
 * @method Help                setDescription()  Sets the current record's "description" value
 * @method Help                setCategory()     Sets the current record's "Category" collection
 * @method Help                setHelpCategory() Sets the current record's "HelpCategory" collection
 * 
 * @package    Tree-of-Life
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHelp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('help');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category', array(
             'refClass' => 'HelpCategory',
             'local' => 'help_id',
             'foreign' => 'category_id'));

        $this->hasMany('HelpCategory', array(
             'local' => 'id',
             'foreign' => 'help_id'));
    }
}