<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $visible
 * @property Need $Need
 * @property Help $Help
 * 
 * @method string   getName()    Returns the current record's "name" value
 * @method boolean  getVisible() Returns the current record's "visible" value
 * @method Need     getNeed()    Returns the current record's "Need" value
 * @method Help     getHelp()    Returns the current record's "Help" value
 * @method Category setName()    Sets the current record's "name" value
 * @method Category setVisible() Sets the current record's "visible" value
 * @method Category setNeed()    Sets the current record's "Need" value
 * @method Category setHelp()    Sets the current record's "Help" value
 * 
 * @package    Tree-of-Life
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Need', array(
             'local' => 'id',
             'foreign' => 'category_id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Help', array(
             'local' => 'id',
             'foreign' => 'category_id',
             'onDelete' => 'SET NULL'));
    }
}