<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $visible
 * @property Doctrine_Collection $Need
 * @property Doctrine_Collection $Help
 * @property Doctrine_Collection $NeedCategory
 * @property Doctrine_Collection $HelpCategory
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method boolean             getVisible()      Returns the current record's "visible" value
 * @method Doctrine_Collection getNeed()         Returns the current record's "Need" collection
 * @method Doctrine_Collection getHelp()         Returns the current record's "Help" collection
 * @method Doctrine_Collection getNeedCategory() Returns the current record's "NeedCategory" collection
 * @method Doctrine_Collection getHelpCategory() Returns the current record's "HelpCategory" collection
 * @method Category            setName()         Sets the current record's "name" value
 * @method Category            setVisible()      Sets the current record's "visible" value
 * @method Category            setNeed()         Sets the current record's "Need" collection
 * @method Category            setHelp()         Sets the current record's "Help" collection
 * @method Category            setNeedCategory() Sets the current record's "NeedCategory" collection
 * @method Category            setHelpCategory() Sets the current record's "HelpCategory" collection
 * 
 * @package    Tree-of-Life
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Need', array(
             'refClass' => 'NeedCategory',
             'local' => 'category_id',
             'foreign' => 'need_id'));

        $this->hasMany('Help', array(
             'refClass' => 'HelpCategory',
             'local' => 'category_id',
             'foreign' => 'help_id'));

        $this->hasMany('NeedCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('HelpCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}