<?php

/**
 * HelpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HelpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HelpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Help');
    }
}