<?php

/**
 * HelpCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HelpCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HelpCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HelpCategory');
    }
}