<?php

/**
 * NeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Need');
    }
}