<?php

/**
 * NeedCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NeedCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NeedCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NeedCategory');
    }
}