
sfGuardUser:
  columns:
    anonymous: {type: boolean, default: false}
    
  

Need: ## flower
  actAs:
    Timestampable: ~
  columns:
    name: {type: string(255)}
    description: {type: string}
    done: {type: boolean, default: false}
  relations:
    Category:
      class: Category
      local: need_id
      foreign: category_id
      refClass: NeedCategory  

NeedCategory:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    need_id: {type: integer, primary: true}
    category_id: {type: integer, primary: true}
  relations:
    Need:
      class: Need
      local: need_id
      onDelete: CASCADE
    Category:
      class: Category
      local: category_id
      onDelete: CASCADE
          
  
Help: ## leaf
  actAs:
    Timestampable: ~
  columns:
    name: {type: string(255)}
    description: {type: string}
  relations:
    Category:
      class: Category
      local: help_id
      foreign: category_id
      refClass: HelpCategory  
   
    
HelpCategory:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    help_id: {type: integer, primary: true}
    category_id: {type: integer, primary: true}
  relations:
    Help:
      class: Help
      local: help_id
      onDelete: CASCADE
    Category:
      class: Category
      local: category_id
      onDelete: CASCADE
      
   
Category: 
  columns:
    name: {type: string(255)}
    visible: {type: boolean, default: true}
  relations:
    Need:
      class: Need
      local: category_id
      foreign: need_id
      refClass: NeedCategory
    Help:
      class: Help
      local: category_id
      foreign: help_id
      refClass: HelpCategory
      
      
      