
sfGuardUser:
  columns:
    anonymous: {type: boolean, default: false}
    
  

Need: ## flower
  actAs:
    Timestampable: ~
  columns:
    name: {type: string(255)}
    description: {type: string}
    done: {type: boolean, default: false}
    category_id: {type: integer}
  relations:
    Category:
      class: Category
      local: category_id
      foreign: id

  
Help: ## leaf
  actAs:
    Timestampable: ~
  columns:
    name: {type: string(255)}
    description: {type: string}
    category_id: {type: integer}
  relations:
    Category:
      class: Category
      local: category_id
      foreign: id
   
    
      
   
Category: 
  columns:
    name: {type: string(255)}
    visible: {type: boolean, default: true}
  relations:
    Need:
      class: Need
      local: id
      foreign: category_id
      onDelete: SET NULL
      
    Help:
      class: Help
      local: id
      foreign: category_id
      onDelete: SET NULL
      
      
      